export type FasProp = {
  firstName: string;
  lastName: string;
  middleName: string;
  gender: string;
  height: string;
  weight: string;
  skin: string;
  hair: string;
  body: string;
  personAd: string;
  personSt: string;
  personLga: string;
  father: string;
  mother: string;
  sibling: string;
  date: string;
  parentAd: string;
  state: string;
  lga: string;
  issueAd: string;
  poName: string;
  poState: string;
  poLga: string;
  poAd: string;
};
